name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional but recommended)
        run: npm test

      - name: Docker Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.yousufuddin }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.yousufuddin }}/nodejs-demo-app .

      - name: Push Docker Image
        run: docker push ${{ secrets.yousufuddin }}/nodejs-demo-app